package com.mycompany.birthdayvault.view;

import com.mycompany.birthdayvault.model.BirthdayEntry;
import com.mycompany.birthdayvault.util.LanguageUtil;
import com.mycompany.birthdayvault.service.MongoDBService;
import java.time.LocalDate;
import java.time.ZoneId;
import javax.swing.JOptionPane;

public class BirthdayAdd extends javax.swing.JFrame {

    private boolean isEditMode = false;
    private BirthdayEntry editingEntry;
    private String username;
    private MongoDBService dbService;
    private String selectedLanguage;

    // Constructor untuk Add Mode (default)
    public BirthdayAdd(String username, String selectedLanguage) {
        this.username = username;
        this.dbService = new MongoDBService();
        this.selectedLanguage = selectedLanguage;

        initComponents();
        setLocationRelativeTo(null);
        labelUser.setText(username);

        // Kosongkan field
        clearForm();

        // Terapkan bahasa
        LanguageUtil.setLanguage(selectedLanguage);
        applyTranslations();
    }
    
    // Constructor untuk Edit Mode
    public BirthdayAdd(String username, BirthdayEntry entry, String selectedLanguage) {
        this.username = username;
        this.dbService = new MongoDBService();
        this.selectedLanguage = selectedLanguage;
        this.isEditMode = true;
        this.editingEntry = entry;

        initComponents();
        setLocationRelativeTo(null);
        labelUser.setText(username);

        // Isi field dengan data yang diedit
        if (entry != null) {
            nameField.setText(entry.getName());
            dateField.setDate(java.sql.Date.valueOf(entry.getBirthDate()));
            messageField.setText(entry.getMessage());
        }

        // Terapkan bahasa
        LanguageUtil.setLanguage(selectedLanguage);
        applyTranslations();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SideBar = new javax.swing.JPanel();
        labelWelcome = new javax.swing.JLabel();
        labelUser = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        logoutButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        mainButton = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        labelAddanniversary = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        labelName = new javax.swing.JLabel();
        LabelDate = new javax.swing.JLabel();
        labelMessage = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        dateField = new com.toedter.calendar.JDateChooser();
        messageField = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SideBar.setBackground(new java.awt.Color(0, 102, 153));

        labelWelcome.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        labelWelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelWelcome.setText("Welcome");

        labelUser.setFont(new java.awt.Font("Segoe Script", 1, 14)); // NOI18N
        labelUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelUser.setText("username");

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        addButton.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        addButton.setText("Add Anniversary");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        mainButton.setText("Anniversary Soon");
        mainButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SideBarLayout = new javax.swing.GroupLayout(SideBar);
        SideBar.setLayout(SideBarLayout);
        SideBarLayout.setHorizontalGroup(
            SideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SideBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelWelcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logoutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mainButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        SideBarLayout.setVerticalGroup(
            SideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SideBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 244, Short.MAX_VALUE)
                .addComponent(logoutButton)
                .addContainerGap())
        );

        getContentPane().add(SideBar, java.awt.BorderLayout.LINE_START);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new java.awt.BorderLayout());

        jLabel3.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("BirthdayVault");

        labelAddanniversary.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        labelAddanniversary.setText("Add Anniversary");

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelAddanniversary)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(97, 97, 97))
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(labelAddanniversary)
                .addGap(4, 4, 4)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel6.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        labelName.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        labelName.setText("Name              =");

        LabelDate.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        LabelDate.setText("Date of birth    =");

        labelMessage.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        labelMessage.setText("Message         =");

        nameField.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        messageField.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        messageField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                messageFieldActionPerformed(evt);
            }
        });

        saveButton.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LabelDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameField)
                            .addComponent(dateField, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(saveButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelMessage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(messageField)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dateField, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                    .addComponent(LabelDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(messageField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(197, 197, 197)
                .addComponent(saveButton)
                .addContainerGap())
        );

        jPanel6.add(jPanel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel6, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mainButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainButtonActionPerformed
        new BirthdayMain(username, selectedLanguage).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mainButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // Ambil dan bersihkan input dari field
        String name = nameField.getText().trim();
        java.util.Date selectedDate = dateField.getDate();
        String message = messageField.getText().trim();

        // Validasi input: semua field wajib diisi
        if (name.isEmpty() || selectedDate == null || message.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Please fill in all fields!",
                    "Warning",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Konversi tanggal dari Date ke LocalDate
        LocalDate birthDate = selectedDate.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();

        if (isEditMode) {
            // Mode edit: konfirmasi pengguna
            int confirm = JOptionPane.showConfirmDialog(this,
                    "Are you sure you want to update this entry?",
                    "Confirm Update",
                    JOptionPane.YES_NO_OPTION);
            if (confirm != JOptionPane.YES_OPTION) {
                return;
            }

            // Update data di database
            BirthdayEntry updated = new BirthdayEntry(username, name, birthDate, message);
            dbService.updateBirthday(username, editingEntry.getName(), updated);

            JOptionPane.showMessageDialog(this, "Updated successfully!");
        } else {
            // Mode tambah: simpan data baru ke database
            BirthdayEntry newEntry = new BirthdayEntry(username, name, birthDate, message);
            dbService.addBirthday(newEntry);

            JOptionPane.showMessageDialog(this, "Birthday added successfully!");
        }

        // Kembali ke halaman utama
        new BirthdayMain(username, selectedLanguage).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_saveButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        new Main().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void messageFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_messageFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_messageFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelDate;
    private javax.swing.JPanel SideBar;
    private javax.swing.JButton addButton;
    private com.toedter.calendar.JDateChooser dateField;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel labelAddanniversary;
    private javax.swing.JLabel labelMessage;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelUser;
    private javax.swing.JLabel labelWelcome;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton mainButton;
    private javax.swing.JTextField messageField;
    private javax.swing.JTextField nameField;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables

    private void clearForm() {
        nameField.setText("");
        dateField.setDate(null);
        messageField.setText("");
    }

    private void applyTranslations() {
        labelWelcome.setText(LanguageUtil.getString("label.welcome"));
        labelName.setText(LanguageUtil.getString("label.name"));
        LabelDate.setText(LanguageUtil.getString("label.date"));
        labelMessage.setText(LanguageUtil.getString("label.message"));
        saveButton.setText(LanguageUtil.getString("button.save"));
        mainButton.setText(LanguageUtil.getString("button.main"));
        logoutButton.setText(LanguageUtil.getString("button.logout"));
        addButton.setText(LanguageUtil.getString("button.add"));
        labelAddanniversary.setText(LanguageUtil.getString("label.addanniversary"));
    }

}
